pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "shreyjain23/product-service:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/shreyjain2003/ecommerce-devops-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('product-service') {
                        sh "docker build -t $DOCKER_IMAGE ."
                    }
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-token',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Clean Up') {
            steps {
                sh 'docker rmi $DOCKER_IMAGE || true'
            }
        }
    }
}
