pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "shreyjain23/product-service:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/shreyjain2003/ecommerce-devops-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('product-service') {
                    bat "docker build -t %DOCKER_IMAGE% ."
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credentials',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {
                    bat 'echo %PASSWORD% | docker login -u %USERNAME% --password-stdin'
                    bat 'docker push %DOCKER_IMAGE%'
                }
            }
        }

        stage('Clean Up') {
            steps {
                bat 'docker rmi %DOCKER_IMAGE% || exit 0'
            }
        }
    }
}
