pipeline {
    agent any

    environment {
        IMAGE_NAME = "shreyjain23/cart-service:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/shreyjain2003/ecommerce-devops-project.git', branch: 'master'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('cart-service') {
                    bat "docker build -t %IMAGE_NAME% ."
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([string(credentialsId: 'docker-hub-password', variable: 'PASSWORD')]) {
                    bat "echo %PASSWORD% | docker login -u shreyjain23 --password-stdin"
                    bat "docker push %IMAGE_NAME%"
                }
            }
        }

        stage('Clean Up') {
            steps {
                bat "docker rmi %IMAGE_NAME% || exit 0"
            }
        }
    }
}
